### ISSUE TITLE
Im getting the following Error:

### ISSUE THREAD

**Issue by julianlaibach** [kboghe/NordVPN-switcher#43]
```
Traceback (most recent call last):
  File "/src/app/crawler.py", line 133, in <module>
    main(settings)
  File "/src/app/crawler.py", line 41, in main
    rotate_VPN(settings)
  File "/usr/local/lib/python3.8/dist-packages/nordvpn_switcher/nordvpn_switch.py", line 457, in rotate_VPN
    current_ip = new_ip = get_ip()
  File "/usr/local/lib/python3.8/dist-packages/nordvpn_switcher/nordvpn_switch.py", line 83, in get_ip
    ip = re.search("IPv4,(.*?),Remaining", ip).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Does anyone has an Solution on that. Thanks a lot!

**Comment by kboghe** [comment]
This should be solved in the latest version available on pypi (0.3.0). 
Could you update your package version and report back whether this has solved your issue? Thanks!
